In [1]:
import numpy as np
np.random.seed(42)
marks = np.array([
    [85, 92, 78, 88],   # Arjun
    [76, 65, 90, 72],   # Priya
    [95, 88, 85, 91],   # Ravi
    [60, 72, 68, 75],   # Sneha
    [88, 95, 92, 87],   # Vikram
])

names = np.array(["Arjun", "Priya", "Ravi", "Sneha", "Vikram"])
subjects = ["Math", "Science", "English", "SST"]

print("📋 Marks Data:")
print(marks)

# Insights using NumPy
print("=" * 50)
print("📊 STUDENT MARKS ANALYSIS")
print("=" * 50)

# 1. Total marks per student (sum along columns = axis 1)
totals = np.sum(marks, axis=1)
print("\nTotal marks per student:")
for name, total in zip(names, totals):
    print(f"  {name:8} : {total}/400  ({total/4:.1f}%)")

# 2. Average per subject (mean along rows = axis 0)
subject_avg = np.mean(marks, axis=0)
print("\nClass average per subject:")
for sub, avg in zip(subjects, subject_avg):
    print(f"  {sub:8} : {avg:.1f}")

# 3. Highest scorer
top_idx = np.argmax(totals)
print(f"\n🏆 TOP STUDENT: {names[top_idx]} with {totals[top_idx]} marks")

# 4. Hardest subject (lowest avg)
hardest_idx = np.argmin(subject_avg)
print(f"😓 HARDEST SUBJECT: {subjects[hardest_idx]} (avg {subject_avg[hardest_idx]:.1f})")

# 5. Students above 80% overall
percentages = totals / 4
above_80 = names[percentages > 80]
print(f"\n⭐ Above 80% : {list(above_80)}")

📋 Marks Data:
[[85 92 78 88]
 [76 65 90 72]
 [95 88 85 91]
 [60 72 68 75]
 [88 95 92 87]]
📊 STUDENT MARKS ANALYSIS

Total marks per student:
  Arjun    : 343/400  (85.8%)
  Priya    : 303/400  (75.8%)
  Ravi     : 359/400  (89.8%)
  Sneha    : 275/400  (68.8%)
  Vikram   : 362/400  (90.5%)

Class average per subject:
  Math     : 80.8
  Science  : 82.4
  English  : 82.6
  SST      : 82.6

🏆 TOP STUDENT: Vikram with 362 marks
😓 HARDEST SUBJECT: Math (avg 80.8)

⭐ Above 80% : [np.str_('Arjun'), np.str_('Ravi'), np.str_('Vikram')]
